import sys
from src.parser import parse_log
from src.detector import process_event, RULES
from src.monitor import monitor
from src.database import save_alert

# Keep count of different types of events
event_count = {
    "authentication_failure": 0,
    "failed_privilege_switch": 0,
    "session_opened": 0,
    "session_closed": 0
}

# Store alerts generated by the detector
alerts = []

# Use test log when --test is passed
log_file = "test_logs/auth.log" if "--test" in sys.argv else "/var/log/auth.log"

# Keep separate state for each detection rule
states = {}
for rule in RULES:
    states[rule["event_type"]] = {}

# Read new log entries continuously
for log in monitor(log_file):
    res = parse_log(log)

    # Update event counters
    match res["event_type"]:
        case "authentication_failure":
            event_count["authentication_failure"] += 1

        case "failed_privilege_switch":
            event_count["failed_privilege_switch"] += 1

        case "session_opened":
            event_count["session_opened"] += 1

        case "session_closed":
            event_count["session_closed"] += 1

    # Check the event against all detection rules
    for rule in RULES:
        alert = process_event(res, rule, states[rule["event_type"]])

        if alert is not None:
            alerts.append(alert)
            save_alert(alert)
            print("ALERT:", alert)